module.exports = [
  "strapi::errors",
  // "strapi::security",
  // 'strapi::cors',
  {
    name: "strapi::cors",
    config: {
      origin: [
        "http://localhost:3000",
        "http://localhost:3001",
        "http://localhost:1337",
        "http://localhost:1338",
        "https://86e9-180-178-138-114.ngrok-free.app",
        "https://7325-180-178-138-114.ngrok-free.app",
        "https://genius-academy-47554.web.app",
        "https://ea88-180-178-138-114.ngrok-free.app",
        "https://2513-180-178-138-114.ngrok-free.app",
        "https://be03-180-178-138-114.ngrok-free.app",
        "https://8cb2-39-51-64-151.ngrok-free.app",
        "https://7dac-39-51-64-151.ngrok-free.app",
        "https://f5c2-180-178-138-114.ngrok-free.app",
        "http://192.168.10.91:3000",
        "https://genius-academy-cms-shop-90dfceeffd52.herokuapp.com",
      ],
      methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"],
      headers: [
        "Content-Type",
        "Authorization",
        "Accept",
        "datatype",
        "Access-Control-Allow-Origin",
        "ngrok-skip-browser-warning",
      ],
      keepHeaderOnError: true,
      credentials: false,
    },
  },
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": ["'self'", "data:", "blob:", "res.cloudinary.com"],
          "media-src": ["'self'", "data:", "blob:", "res.cloudinary.com"],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
];
